version: '3.9'

services:
  time-tracker-db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: "time-tracker-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "-U", "postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    ports:
      - "5432:5432"



