version: '3.9'

services:
  postgres:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: "time-tracker-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "-U", "postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    ports:
      - "5434:5432"
  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/migration:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres